meta:
  url: https://slide.hiroppy.me
  title: issues
  description: Introduce Fusuma
  thumbnail: https://avatars0.githubusercontent.com/u/3367801?s=400&v=4
  siteName: hiroppy.me
  sns: ['twitter']
slide:
  showIndex: true
  code:
    languages:
      - yaml
      - json
      - markdown
      - javascript
      - css
