meta:
  url: https://slide.hiroppy.me
  title: issues
  description: A place which produces to resolve issues
  thumbnail: https://avatars0.githubusercontent.com/u/3367801?s=400&v=4
  siteName: hiroppy.me
  sns: ['twitter']
